package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigInteger;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.ExtensionsType;

public class BasicRequestType extends AttributeContainer implements KvmSerializable
{
    
    public String FunctionCallIdentifier;
    
    public BigInteger ValidityPeriod;
    
    public ArrayList< ExtensionsType>Extensions =new ArrayList<ExtensionsType>();

    public BasicRequestType ()
    {
    }

    public BasicRequestType (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("FunctionCallIdentifier"))
        {	
	        java.lang.Object obj = soapObject.getProperty("FunctionCallIdentifier");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.FunctionCallIdentifier = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.FunctionCallIdentifier = (String)obj;
            }    
        }
        if (soapObject.hasProperty("ValidityPeriod"))
        {	
	        java.lang.Object obj = soapObject.getProperty("ValidityPeriod");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ValidityPeriod = new BigInteger(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof BigInteger){
                this.ValidityPeriod = (BigInteger)obj;
            }    
        }
        if (soapObject.hasProperty("Extensions"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.Extensions = new ArrayList<ExtensionsType>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("Extensions"))
	            {
                    java.lang.Object j =info.getValue();
	                ExtensionsType j1= (ExtensionsType)envelope.get(j,ExtensionsType.class);
	                this.Extensions.add(j1);
	            }
	        }
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return FunctionCallIdentifier!=null?FunctionCallIdentifier:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return ValidityPeriod!=null?ValidityPeriod.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=+2 && propertyIndex< + 2+this.Extensions.size())
        {
            return Extensions.get(propertyIndex-(+2));
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2+Extensions.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FunctionCallIdentifier";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ValidityPeriod";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex>=+2 && propertyIndex <= +2+this.Extensions.size())
        {
            info.type = ExtensionsType.class;
            info.name = "Extensions";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
