package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;


import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.ServiceInstanceReferenceType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.ExchangeServiceDataCommandType;

public class ExchangeServiceDataRequestType extends BasicRequestType implements KvmSerializable
{
    
    public ServiceInstanceReferenceType ServiceInstanceReference;
    
    public ArrayList< ExchangeServiceDataCommandType>ExchangeServiceDataCommand =new ArrayList<ExchangeServiceDataCommandType>();

    public ExchangeServiceDataRequestType ()
    {
    }

    public ExchangeServiceDataRequestType (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    super(inObj, envelope);
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("ServiceInstanceReference"))
        {	
	        java.lang.Object j = soapObject.getProperty("ServiceInstanceReference");
	        this.ServiceInstanceReference = (ServiceInstanceReferenceType)envelope.get(j,ServiceInstanceReferenceType.class);
        }
        if (soapObject.hasProperty("ExchangeServiceDataCommand"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.ExchangeServiceDataCommand = new ArrayList<ExchangeServiceDataCommandType>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("ExchangeServiceDataCommand"))
	            {
                    java.lang.Object j =info.getValue();
	                ExchangeServiceDataCommandType j1= (ExchangeServiceDataCommandType)envelope.get(j,ExchangeServiceDataCommandType.class);
	                this.ExchangeServiceDataCommand.add(j1);
	            }
	        }
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using org.mbds.wolf.tsm.gp.systems.messaging2_1_0 version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return ServiceInstanceReference;
        }
        if(propertyIndex>=count+1 && propertyIndex< count+ 1+this.ExchangeServiceDataCommand.size())
        {
            return ExchangeServiceDataCommand.get(propertyIndex-(count+1));
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+1+ExchangeServiceDataCommand.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = ServiceInstanceReferenceType.class;
            info.name = "ServiceInstanceReference";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex>=count+1 && propertyIndex <= count+1+this.ExchangeServiceDataCommand.size())
        {
            info.type = ExchangeServiceDataCommandType.class;
            info.name = "ExchangeServiceDataCommand";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
