package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.Helper;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.ServiceInstanceReferenceType;

import java.math.BigInteger;

public class HandleServiceEnvironmentChangeNotificationRequestType extends BasicRequestType implements KvmSerializable
{
    
    public ServiceInstanceReferenceType ServiceInstanceReference;
    
    public BigInteger Event=BigInteger.ZERO;
    
    public java.util.Date Date;
    
    public BigInteger NewServiceInstanceState=BigInteger.ZERO;

    public HandleServiceEnvironmentChangeNotificationRequestType ()
    {
    }

    public HandleServiceEnvironmentChangeNotificationRequestType (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    super(inObj, envelope);
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("ServiceInstanceReference"))
        {	
	        java.lang.Object j = soapObject.getProperty("ServiceInstanceReference");
	        this.ServiceInstanceReference = (ServiceInstanceReferenceType)envelope.get(j,ServiceInstanceReferenceType.class);
        }
        if (soapObject.hasProperty("Event"))
        {	
	        java.lang.Object obj = soapObject.getProperty("Event");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Event = new BigInteger(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof BigInteger){
                this.Event = (BigInteger)obj;
            }    
        }
        if (soapObject.hasProperty("Date"))
        {	
	        java.lang.Object obj = soapObject.getProperty("Date");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Date = Helper.ConvertFromWebService(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof java.util.Date){
                this.Date = (java.util.Date)obj;
            }    
        }
        if (soapObject.hasProperty("NewServiceInstanceState"))
        {	
	        java.lang.Object obj = soapObject.getProperty("NewServiceInstanceState");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.NewServiceInstanceState = new BigInteger(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof BigInteger){
                this.NewServiceInstanceState = (BigInteger)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return ServiceInstanceReference;
        }
        if(propertyIndex==count+1)
        {
            return Event!=null?Event.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+2)
        {
            return Date!=null?Date:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+3)
        {
            return NewServiceInstanceState!=null?NewServiceInstanceState.toString():SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = ServiceInstanceReferenceType.class;
            info.name = "ServiceInstanceReference";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Event";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Date";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "NewServiceInstanceState";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
