package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.Enums;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.MobileSubscriptionIdentifierType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.ServiceIdentifierType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.ServiceQualifierType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.Enums.ActionOnDeviceExecutionStatusType;

import java.math.BigInteger;

public class HandleActionDoneOnDeviceApplicationNotificationRequestType extends BasicRequestType implements KvmSerializable
{
    
    public MobileSubscriptionIdentifierType MobileSubscription;
    
    public ServiceIdentifierType Service;
    
    public ServiceQualifierType ServiceQualifier;
    
    public String DeviceApplicationIdentifier;
    
    public BigInteger Action=BigInteger.ZERO;
    
    public Enums.ActionOnDeviceExecutionStatusType ActionExecutionStatus=Enums.ActionOnDeviceExecutionStatusType.EXECUTED_SUCCESS;

    public HandleActionDoneOnDeviceApplicationNotificationRequestType ()
    {
    }

    public HandleActionDoneOnDeviceApplicationNotificationRequestType (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    super(inObj, envelope);
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("MobileSubscription"))
        {	
	        java.lang.Object j = soapObject.getProperty("MobileSubscription");
	        this.MobileSubscription = (MobileSubscriptionIdentifierType)envelope.get(j,MobileSubscriptionIdentifierType.class);
        }
        if (soapObject.hasProperty("Service"))
        {	
	        java.lang.Object j = soapObject.getProperty("Service");
	        this.Service = (ServiceIdentifierType)envelope.get(j,ServiceIdentifierType.class);
        }
        if (soapObject.hasProperty("ServiceQualifier"))
        {	
	        java.lang.Object j = soapObject.getProperty("ServiceQualifier");
	        this.ServiceQualifier = (ServiceQualifierType)envelope.get(j,ServiceQualifierType.class);
        }
        if (soapObject.hasProperty("DeviceApplicationIdentifier"))
        {	
	        java.lang.Object obj = soapObject.getProperty("DeviceApplicationIdentifier");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.DeviceApplicationIdentifier = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.DeviceApplicationIdentifier = (String)obj;
            }    
        }
        if (soapObject.hasProperty("Action"))
        {	
	        java.lang.Object obj = soapObject.getProperty("Action");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Action = new BigInteger(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof BigInteger){
                this.Action = (BigInteger)obj;
            }    
        }
        if (soapObject.hasProperty("ActionExecutionStatus"))
        {	
	        java.lang.Object obj = soapObject.getProperty("ActionExecutionStatus");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ActionExecutionStatus = Enums.ActionOnDeviceExecutionStatusType.fromString(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Enums.ActionOnDeviceExecutionStatusType){
                this.ActionExecutionStatus = (Enums.ActionOnDeviceExecutionStatusType)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return MobileSubscription;
        }
        if(propertyIndex==count+1)
        {
            return Service;
        }
        if(propertyIndex==count+2)
        {
            return ServiceQualifier!=null?ServiceQualifier:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+3)
        {
            return DeviceApplicationIdentifier!=null?DeviceApplicationIdentifier:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+4)
        {
            return Action!=null?Action.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+5)
        {
            return ActionExecutionStatus!=null?ActionExecutionStatus.toString():SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = MobileSubscriptionIdentifierType.class;
            info.name = "MobileSubscription";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+1)
        {
            info.type = ServiceIdentifierType.class;
            info.name = "Service";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+2)
        {
            info.type = ServiceQualifierType.class;
            info.name = "ServiceQualifier";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DeviceApplicationIdentifier";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Action";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ActionExecutionStatus";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
