package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.math.BigInteger;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.SEApplicationIdentifierType;

public class SendScriptRequestType extends BasicRequestType implements KvmSerializable
{
    
    public BigInteger ConversationID=BigInteger.ZERO;
    
    public SEApplicationIdentifierType TargetIdentifier;
    
    public ArrayList< String>CommandAPDU =new ArrayList<String>();

    public SendScriptRequestType ()
    {
    }

    public SendScriptRequestType (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    super(inObj, envelope);
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("ConversationID"))
        {	
	        java.lang.Object obj = soapObject.getProperty("ConversationID");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ConversationID = new BigInteger(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof BigInteger){
                this.ConversationID = (BigInteger)obj;
            }    
        }
        if (soapObject.hasProperty("TargetIdentifier"))
        {	
	        java.lang.Object j = soapObject.getProperty("TargetIdentifier");
	        this.TargetIdentifier = (SEApplicationIdentifierType)envelope.get(j,SEApplicationIdentifierType.class);
        }
        if (soapObject.hasProperty("CommandAPDU"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.CommandAPDU = new ArrayList<String>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("CommandAPDU"))
	            {
                    java.lang.Object j =info.getValue();
	                String j1= j.toString();
	                this.CommandAPDU.add(j1);
	            }
	        }
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return ConversationID!=null?ConversationID.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+1)
        {
            return TargetIdentifier!=null?TargetIdentifier:SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=count+2 && propertyIndex< count+ 2+this.CommandAPDU.size())
        {
            return CommandAPDU.get(propertyIndex-(count+2));
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+2+CommandAPDU.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ConversationID";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+1)
        {
            info.type = SEApplicationIdentifierType.class;
            info.name = "TargetIdentifier";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex>=count+2 && propertyIndex <= count+2+this.CommandAPDU.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "CommandAPDU";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
