package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;

public class Entity_Contact extends AttributeContainer implements KvmSerializable
{
    
    public Person Person;
    
    public ArrayList< String>PhoneNumber =new ArrayList<String>();
    
    public ArrayList< String>FaxNumber =new ArrayList<String>();
    
    public ArrayList< String>eMail =new ArrayList<String>();
    
    public ArrayList< String>URL =new ArrayList<String>();
    
    public Information Information;
    
    public String Name;

    public Entity_Contact ()
    {
    }

    public Entity_Contact (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("Person"))
        {	
	        java.lang.Object j = soapObject.getProperty("Person");
	        this.Person = (Person)envelope.get(j,Person.class);
        }
        if (soapObject.hasProperty("PhoneNumber"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.PhoneNumber = new ArrayList<String>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("PhoneNumber"))
	            {
                    java.lang.Object j =info.getValue();
	                String j1= j.toString();
	                this.PhoneNumber.add(j1);
	            }
	        }
        }
        if (soapObject.hasProperty("FaxNumber"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.FaxNumber = new ArrayList<String>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("FaxNumber"))
	            {
                    java.lang.Object j =info.getValue();
	                String j1= j.toString();
	                this.FaxNumber.add(j1);
	            }
	        }
        }
        if (soapObject.hasProperty("eMail"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.eMail = new ArrayList<String>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("eMail"))
	            {
                    java.lang.Object j =info.getValue();
	                String j1= j.toString();
	                this.eMail.add(j1);
	            }
	        }
        }
        if (soapObject.hasProperty("URL"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.URL = new ArrayList<String>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("URL"))
	            {
                    java.lang.Object j =info.getValue();
	                String j1= j.toString();
	                this.URL.add(j1);
	            }
	        }
        }
        if (soapObject.hasProperty("Information"))
        {	
	        java.lang.Object j = soapObject.getProperty("Information");
	        this.Information = (Information)envelope.get(j,Information.class);
        }


        if (inObj.hasAttribute("Name"))
        {	
            java.lang.Object j = inObj.getAttribute("Name");
            if (j != null)
            {
	            Name = j.toString();
            }
        }

    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return Person;
        }
        if(propertyIndex==1)
        {
            return Information;
        }
        if(propertyIndex>=+2 && propertyIndex< + 2+this.PhoneNumber.size())
        {
            return PhoneNumber.get(propertyIndex-(+2));
        }
        if(propertyIndex>=+2+this.PhoneNumber.size() && propertyIndex< + 2+this.PhoneNumber.size()+this.FaxNumber.size())
        {
            return FaxNumber.get(propertyIndex-(+2+this.PhoneNumber.size()));
        }
        if(propertyIndex>=+2+this.PhoneNumber.size()+this.FaxNumber.size() && propertyIndex< + 2+this.PhoneNumber.size()+this.FaxNumber.size()+this.eMail.size())
        {
            return eMail.get(propertyIndex-(+2+this.PhoneNumber.size()+this.FaxNumber.size()));
        }
        if(propertyIndex>=+2+this.PhoneNumber.size()+this.FaxNumber.size()+this.eMail.size() && propertyIndex< + 2+this.PhoneNumber.size()+this.FaxNumber.size()+this.eMail.size()+this.URL.size())
        {
            return URL.get(propertyIndex-(+2+this.PhoneNumber.size()+this.FaxNumber.size()+this.eMail.size()));
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2+PhoneNumber.size()+FaxNumber.size()+eMail.size()+URL.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = Person.class;
            info.name = "Person";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==1)
        {
            info.type = Information.class;
            info.name = "Information";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex>=+2 && propertyIndex <= +2+this.PhoneNumber.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PhoneNumber";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex>=+2+this.PhoneNumber.size() && propertyIndex <= +2+this.PhoneNumber.size()+this.FaxNumber.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "FaxNumber";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex>=+2+this.PhoneNumber.size()+this.FaxNumber.size() && propertyIndex <= +2+this.PhoneNumber.size()+this.FaxNumber.size()+this.eMail.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "eMail";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex>=+2+this.PhoneNumber.size()+this.FaxNumber.size()+this.eMail.size() && propertyIndex <= +2+this.PhoneNumber.size()+this.FaxNumber.size()+this.eMail.size()+this.URL.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "URL";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }


    @Override
    public int getAttributeCount() {
        return 1;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "Name";
            info.namespace= "";
            info.setValue(Name);
        }
    }}
