package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;

public class Entity extends AttributeContainer implements KvmSerializable
{
    
    public Address Address;
    
    public Entity_Contact Contact;
    
    public String Name;

    public Entity ()
    {
    }

    public Entity (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("Address"))
        {	
	        java.lang.Object j = soapObject.getProperty("Address");
	        this.Address = (Address)envelope.get(j,Address.class);
        }
        if (soapObject.hasProperty("Contact"))
        {	
	        java.lang.Object j = soapObject.getProperty("Contact");
	        this.Contact = (Entity_Contact)envelope.get(j,Entity_Contact.class);
        }


        if (inObj.hasAttribute("Name"))
        {	
            java.lang.Object j = inObj.getAttribute("Name");
            if (j != null)
            {
	            Name = j.toString();
            }
        }

    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return Address;
        }
        if(propertyIndex==1)
        {
            return Contact!=null?Contact:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = Address.class;
            info.name = "Address";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==1)
        {
            info.type = Entity_Contact.class;
            info.name = "Contact";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }


    @Override
    public int getAttributeCount() {
        return 1;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "Name";
            info.namespace= "";
            info.setValue(Name);
        }
    }}
