package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;

public class ModuleIdentifierCode extends AttributeContainer implements KvmSerializable
{
    
    public CardConfiguration CardConfiguration;
    
    public ArrayList< ApplicationData>ApplicationData =new ArrayList<ApplicationData>();
    
    public String Identifier;

    public ModuleIdentifierCode ()
    {
    }

    public ModuleIdentifierCode (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("CardConfiguration"))
        {	
	        java.lang.Object j = soapObject.getProperty("CardConfiguration");
	        this.CardConfiguration = (CardConfiguration)envelope.get(j,CardConfiguration.class);
        }
        if (soapObject.hasProperty("ApplicationData"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.ApplicationData = new ArrayList<ApplicationData>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("ApplicationData"))
	            {
                    java.lang.Object j =info.getValue();
	                ApplicationData j1= (ApplicationData)envelope.get(j,ApplicationData.class);
	                this.ApplicationData.add(j1);
	            }
	        }
        }


        if (inObj.hasAttribute("Identifier"))
        {	
            java.lang.Object j = inObj.getAttribute("Identifier");
            if (j != null)
            {
	            Identifier = j.toString();
            }
        }

    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return CardConfiguration;
        }
        if(propertyIndex>=+1 && propertyIndex< + 1+this.ApplicationData.size())
        {
            return ApplicationData.get(propertyIndex-(+1));
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 1+ApplicationData.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = CardConfiguration.class;
            info.name = "CardConfiguration";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex>=+1 && propertyIndex <= +1+this.ApplicationData.size())
        {
            info.type = ApplicationData.class;
            info.name = "ApplicationData";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }


    @Override
    public int getAttributeCount() {
        return 1;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "Identifier";
            info.namespace= "";
            info.setValue(Identifier);
        }
    }}
