package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;


import org.ksoap2.serialization.*;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.GetMobileSubscriptionAlternateIdentifierResponseDataType;

public class GetMobileSubscriptionAlternateIdentifierResponseType extends BasicResponseType implements KvmSerializable
{
    
    public GetMobileSubscriptionAlternateIdentifierResponseDataType ResponseData;

    public GetMobileSubscriptionAlternateIdentifierResponseType ()
    {
    }

    public GetMobileSubscriptionAlternateIdentifierResponseType (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    super(inObj, envelope);
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("ResponseData"))
        {	
	        java.lang.Object j = soapObject.getProperty("ResponseData");
	        this.ResponseData = (GetMobileSubscriptionAlternateIdentifierResponseDataType)envelope.get(j,GetMobileSubscriptionAlternateIdentifierResponseDataType.class);
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using org.mbds.wolf.tsm.gp.systems.messaging2_1_0 version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return ResponseData!=null?ResponseData:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+1;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = GetMobileSubscriptionAlternateIdentifierResponseDataType.class;
            info.name = "ResponseData";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
