package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;


import org.ksoap2.serialization.*;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.Enums;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.Enums.ECCKeyLengthType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.Enums.KeyGenerationModeType;

public class CCCMScenario3_CreateFirstSSDKeysetCommandType extends CreateFirstSSDKeysetCommandType implements KvmSerializable
{
    
    public String SDIN;
    
    public Enums.KeyGenerationModeType KeyGenerationMode=Enums.KeyGenerationModeType._1_SECURE_CHANNEL_BASE_KEY;
    
    public Enums.ECCKeyLengthType ECCKeyLength=Enums.ECCKeyLengthType.ECC_x002D_256;
    
    public Integer ScenarioParameter=0;
    
    public String HostID;
    
    public String SSDOwnerEphemeralPublicKey;

    public CCCMScenario3_CreateFirstSSDKeysetCommandType ()
    {
    }

    public CCCMScenario3_CreateFirstSSDKeysetCommandType (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    super(inObj, envelope);
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("SDIN"))
        {	
	        java.lang.Object obj = soapObject.getProperty("SDIN");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.SDIN = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.SDIN = (String)obj;
            }    
        }
        if (soapObject.hasProperty("KeyGenerationMode"))
        {	
	        java.lang.Object obj = soapObject.getProperty("KeyGenerationMode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.KeyGenerationMode = Enums.KeyGenerationModeType.fromString(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Enums.KeyGenerationModeType){
                this.KeyGenerationMode = (Enums.KeyGenerationModeType)obj;
            }    
        }
        if (soapObject.hasProperty("ECCKeyLength"))
        {	
	        java.lang.Object obj = soapObject.getProperty("ECCKeyLength");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ECCKeyLength = Enums.ECCKeyLengthType.fromString(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Enums.ECCKeyLengthType){
                this.ECCKeyLength = (Enums.ECCKeyLengthType)obj;
            }    
        }
        if (soapObject.hasProperty("ScenarioParameter"))
        {	
	        java.lang.Object obj = soapObject.getProperty("ScenarioParameter");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ScenarioParameter = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.ScenarioParameter = (Integer)obj;
            }    
        }
        if (soapObject.hasProperty("HostID"))
        {	
	        java.lang.Object obj = soapObject.getProperty("HostID");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.HostID = j.toString();
                }
	        }
	        else if (obj!= null){
                this.HostID = obj.toString();
            }    
        }
        if (soapObject.hasProperty("SSDOwnerEphemeralPublicKey"))
        {	
	        java.lang.Object obj = soapObject.getProperty("SSDOwnerEphemeralPublicKey");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.SSDOwnerEphemeralPublicKey = j.toString();
                }
	        }
	        else if (obj!= null){
                this.SSDOwnerEphemeralPublicKey = obj.toString();
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using org.mbds.wolf.tsm.gp.systems.messaging2_1_0 version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return SDIN!=null?SDIN:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+1)
        {
            return KeyGenerationMode!=null?KeyGenerationMode.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+2)
        {
            return ECCKeyLength!=null?ECCKeyLength.toString():SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+3)
        {
            return ScenarioParameter;
        }
        if(propertyIndex==count+4)
        {
            return HostID!=null?HostID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+5)
        {
            return SSDOwnerEphemeralPublicKey;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+6;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SDIN";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "KeyGenerationMode";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ECCKeyLength";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+3)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ScenarioParameter";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+4)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "HostID";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+5)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SSDOwnerEphemeralPublicKey";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
