package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.KeySetDescriptionType;

public class CreateFirstSSDKeysetCommandType extends SECommandType implements KvmSerializable
{
    
    public String SSDAID;
    
    public KeySetDescriptionType KeySetDescription;
    
    public Integer KeyVersionNumber=0;
    
    public String InitialSequenceCounter;

    public CreateFirstSSDKeysetCommandType ()
    {
    }

    public CreateFirstSSDKeysetCommandType (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    super(inObj, envelope);
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("SSDAID"))
        {	
	        java.lang.Object obj = soapObject.getProperty("SSDAID");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.SSDAID = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.SSDAID = (String)obj;
            }    
        }
        if (soapObject.hasProperty("KeySetDescription"))
        {	
	        java.lang.Object j = soapObject.getProperty("KeySetDescription");
	        this.KeySetDescription = (KeySetDescriptionType)envelope.get(j,KeySetDescriptionType.class);
        }
        if (soapObject.hasProperty("KeyVersionNumber"))
        {	
	        java.lang.Object obj = soapObject.getProperty("KeyVersionNumber");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.KeyVersionNumber = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.KeyVersionNumber = (Integer)obj;
            }    
        }
        if (soapObject.hasProperty("InitialSequenceCounter"))
        {	
	        java.lang.Object obj = soapObject.getProperty("InitialSequenceCounter");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.InitialSequenceCounter = j.toString();
                }
	        }
	        else if (obj!= null){
                this.InitialSequenceCounter = obj.toString();
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return SSDAID!=null?SSDAID:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+1)
        {
            return KeySetDescription!=null?KeySetDescription:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+2)
        {
            return KeyVersionNumber;
        }
        if(propertyIndex==count+3)
        {
            return InitialSequenceCounter!=null?InitialSequenceCounter:SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SSDAID";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+1)
        {
            info.type = KeySetDescriptionType.class;
            info.name = "KeySetDescription";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "KeyVersionNumber";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "InitialSequenceCounter";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
