package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;


import org.ksoap2.serialization.*;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.Enums;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.Enums.SEObjectDeletionModeType;

public class DeleteCommandType extends SECommandType implements KvmSerializable
{
    
    public String ApplicationOrExecutableLoadFileAID;
    
    public Boolean DeleteRelatedObjects;
    
    public Enums.SEObjectDeletionModeType SEObjectDeletionMode;

    public DeleteCommandType ()
    {
    }

    public DeleteCommandType (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    super(inObj, envelope);
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("ApplicationOrExecutableLoadFileAID"))
        {	
	        java.lang.Object obj = soapObject.getProperty("ApplicationOrExecutableLoadFileAID");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ApplicationOrExecutableLoadFileAID = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.ApplicationOrExecutableLoadFileAID = (String)obj;
            }    
        }
        if (soapObject.hasProperty("DeleteRelatedObjects"))
        {	
	        java.lang.Object obj = soapObject.getProperty("DeleteRelatedObjects");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.DeleteRelatedObjects = new Boolean(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Boolean){
                this.DeleteRelatedObjects = (Boolean)obj;
            }    
        }
        if (soapObject.hasProperty("SEObjectDeletionMode"))
        {	
	        java.lang.Object obj = soapObject.getProperty("SEObjectDeletionMode");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.SEObjectDeletionMode = Enums.SEObjectDeletionModeType.fromString(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Enums.SEObjectDeletionModeType){
                this.SEObjectDeletionMode = (Enums.SEObjectDeletionModeType)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using org.mbds.wolf.tsm.gp.systems.messaging2_1_0 version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return ApplicationOrExecutableLoadFileAID;
        }
        if(propertyIndex==count+1)
        {
            return DeleteRelatedObjects!=null?DeleteRelatedObjects:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==count+2)
        {
            return SEObjectDeletionMode!=null?SEObjectDeletionMode.toString():SoapPrimitive.NullSkip;
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ApplicationOrExecutableLoadFileAID";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+1)
        {
            info.type = PropertyInfo.BOOLEAN_CLASS;
            info.name = "DeleteRelatedObjects";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==count+2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SEObjectDeletionMode";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
