package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.ArrayList;
import java.util.Hashtable;


import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;

public class Application_ComponentStatusType extends ComponentStatusType implements KvmSerializable
{
    
    public ArrayList< Enums.SEApplicationLifeCycleType>ApplicationLifeCycle =new ArrayList<Enums.SEApplicationLifeCycleType>();
    
    public Integer ApplicationSpecificBits;

    public Application_ComponentStatusType ()
    {
    }

    public Application_ComponentStatusType (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    super(inObj, envelope);
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("ApplicationLifeCycle"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.ApplicationLifeCycle = new ArrayList<Enums.SEApplicationLifeCycleType>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("ApplicationLifeCycle"))
	            {
                    java.lang.Object j =info.getValue();
	                Enums.SEApplicationLifeCycleType j1= Enums.SEApplicationLifeCycleType.fromString(j.toString());
	                this.ApplicationLifeCycle.add(j1);
	            }
	        }
        }
        if (soapObject.hasProperty("ApplicationSpecificBits"))
        {	
	        java.lang.Object obj = soapObject.getProperty("ApplicationSpecificBits");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ApplicationSpecificBits = Integer.parseInt(j.toString());
                }
	        }
	        else if (obj!= null && obj instanceof Integer){
                this.ApplicationSpecificBits = (Integer)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using org.mbds.wolf.tsm.gp.systems.messaging2_1_0 version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==count+0)
        {
            return ApplicationSpecificBits!=null?ApplicationSpecificBits:SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=count+1 && propertyIndex< count+ 1+this.ApplicationLifeCycle.size())
        {
            return ApplicationLifeCycle.get(propertyIndex-(count+1));
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+1+ApplicationLifeCycle.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex==count+0)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "ApplicationSpecificBits";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex>=count+1 && propertyIndex <= count+1+this.ApplicationLifeCycle.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ApplicationLifeCycle";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
