package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.Helper;

public class PGPDataType extends AttributeContainer implements KvmSerializable
{
    
    public String PGPKeyID;
    
    public String PGPKeyPacket;
    
    public String PGPKeyPacket_1;

    public PGPDataType ()
    {
    }

    public PGPDataType (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("PGPKeyID"))
        {	
	        java.lang.Object obj = soapObject.getProperty("PGPKeyID");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.PGPKeyID = j.toString();
                }
	        }
	        else if (obj!= null){
                this.PGPKeyID = obj.toString();
            }    
        }
        if (soapObject.hasProperty("PGPKeyPacket"))
        {
            java.util.ArrayList< PropertyInfo> list=Helper.getProperties(soapObject,"PGPKeyPacket");
            
            for (int i0=0;i0< list.size();i0++)
            {
                PropertyInfo info=list.get(i0);
                java.lang.Object obj = info.getValue();
                if (i0 == 0)
                {
	                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.PGPKeyPacket = j.toString();
                        }
	                }
	                else if (obj!= null){
                        this.PGPKeyPacket = obj.toString();
                    }    
                }
                if (i0 == 1)
                {
	                if (obj != null && obj.getClass().equals(SoapPrimitive.class))
                    {
                        SoapPrimitive j =(SoapPrimitive) obj;
                        if(j.toString()!=null)
                        {
                            this.PGPKeyPacket_1 = j.toString();
                        }
	                }
	                else if (obj!= null){
                        this.PGPKeyPacket_1 = obj.toString();
                    }    
                }
            
            }
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return PGPKeyID;
        }
        if(propertyIndex==1)
        {
            return PGPKeyPacket!=null?PGPKeyPacket:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return PGPKeyPacket_1;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PGPKeyID";
            info.namespace= "http://www.w3.org/2000/09/xmldsig#";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PGPKeyPacket";
            info.namespace= "http://www.w3.org/2000/09/xmldsig#";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "PGPKeyPacket";
            info.namespace= "http://www.w3.org/2000/09/xmldsig#";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
