package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;


import org.ksoap2.serialization.*;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;

public class ReferenceType extends AttributeContainer implements KvmSerializable
{
    
    public TransformsType Transforms=new TransformsType();
    
    public DigestMethodType DigestMethod;
    
    public String DigestValue;
    
    public String Id;
    
    public String URI;
    
    public String Type;

    public ReferenceType ()
    {
    }

    public ReferenceType (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("Transforms"))
        {	
	        java.lang.Object j = soapObject.getProperty("Transforms");
	        this.Transforms = new TransformsType((AttributeContainer)j,envelope);
        }
        if (soapObject.hasProperty("DigestMethod"))
        {	
	        java.lang.Object j = soapObject.getProperty("DigestMethod");
	        this.DigestMethod = (DigestMethodType)envelope.get(j,DigestMethodType.class);
        }
        if (soapObject.hasProperty("DigestValue"))
        {	
	        java.lang.Object obj = soapObject.getProperty("DigestValue");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.DigestValue = j.toString();
                }
	        }
	        else if (obj!= null){
                this.DigestValue = obj.toString();
            }    
        }


        if (inObj.hasAttribute("Id"))
        {	
            java.lang.Object j = inObj.getAttribute("Id");
            if (j != null)
            {
	            Id = j.toString();
            }
        }

        if (inObj.hasAttribute("URI"))
        {	
            java.lang.Object j = inObj.getAttribute("URI");
            if (j != null)
            {
	            URI = j.toString();
            }
        }

        if (inObj.hasAttribute("Type"))
        {	
            java.lang.Object j = inObj.getAttribute("Type");
            if (j != null)
            {
	            Type = j.toString();
            }
        }

    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using org.mbds.wolf.tsm.gp.systems.messaging2_1_0 version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return Transforms;
        }
        if(propertyIndex==1)
        {
            return DigestMethod;
        }
        if(propertyIndex==2)
        {
            return DigestValue;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "Transforms";
            info.namespace= "http://www.w3.org/2000/09/xmldsig#";
        }
        if(propertyIndex==1)
        {
            info.type = DigestMethodType.class;
            info.name = "DigestMethod";
            info.namespace= "http://www.w3.org/2000/09/xmldsig#";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "DigestValue";
            info.namespace= "http://www.w3.org/2000/09/xmldsig#";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }


    @Override
    public int getAttributeCount() {
        return 3;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "Id";
            info.namespace= "";
            info.setValue(Id);
        }
        if(index==1)
        {
            info.name = "URI";
            info.namespace= "";
            info.setValue(URI);
        }
        if(index==2)
        {
            info.name = "Type";
            info.namespace= "";
            info.setValue(Type);
        }
    }}
