package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;


import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.Enums.SDLifeCycleType;

public class SD_ComponentStatusType extends ComponentStatusType implements KvmSerializable
{
    
    public ArrayList< Enums.SDLifeCycleType>SDLifeCycle =new ArrayList<Enums.SDLifeCycleType>();
    
    public ArrayList< ComponentStatusType>DescendantComponent =new ArrayList<ComponentStatusType>();

    public SD_ComponentStatusType ()
    {
    }

    public SD_ComponentStatusType (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    super(inObj, envelope);
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("SDLifeCycle"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.SDLifeCycle = new ArrayList<Enums.SDLifeCycleType>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("SDLifeCycle"))
	            {
                    java.lang.Object j =info.getValue();
	                Enums.SDLifeCycleType j1= Enums.SDLifeCycleType.fromString(j.toString());
	                this.SDLifeCycle.add(j1);
	            }
	        }
        }
        if (soapObject.hasProperty("DescendantComponent"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.DescendantComponent = new ArrayList<ComponentStatusType>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("DescendantComponent"))
	            {
                    java.lang.Object j =info.getValue();
	                ComponentStatusType j1= (ComponentStatusType)envelope.get(j,ComponentStatusType.class);
	                this.DescendantComponent.add(j1);
	            }
	        }
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        int count = super.getPropertyCount();
        //!!!!! If you have a compilation error here then you are using org.mbds.wolf.tsm.gp.systems.messaging2_1_0 version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex>=count+0 && propertyIndex< count+ 0+this.SDLifeCycle.size())
        {
            return SDLifeCycle.get(propertyIndex-(count+0));
        }
        if(propertyIndex>=count+0+this.SDLifeCycle.size() && propertyIndex< count+ 0+this.SDLifeCycle.size()+this.DescendantComponent.size())
        {
            return DescendantComponent.get(propertyIndex-(count+0+this.SDLifeCycle.size()));
        }
        return super.getProperty(propertyIndex);
    }


    @Override
    public int getPropertyCount() {
        return super.getPropertyCount()+0+SDLifeCycle.size()+DescendantComponent.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        int count = super.getPropertyCount();
        if(propertyIndex>=count+0 && propertyIndex <= count+0+this.SDLifeCycle.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "SDLifeCycle";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex>=count+0+this.SDLifeCycle.size() && propertyIndex <= count+0+this.SDLifeCycle.size()+this.DescendantComponent.size())
        {
            info.type = ComponentStatusType.class;
            info.name = "DescendantComponent";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        super.getPropertyInfo(propertyIndex,arg1,info);
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
