package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;


import org.ksoap2.serialization.*;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;

public class ServiceVersionType extends AttributeContainer implements KvmSerializable
{
    
    public String MajorVersion;
    
    public String MinorVersion;
    
    public String RevisionVersion;

    public ServiceVersionType ()
    {
    }

    public ServiceVersionType (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("MajorVersion"))
        {	
	        java.lang.Object obj = soapObject.getProperty("MajorVersion");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.MajorVersion = j.toString();
                }
	        }
	        else if (obj!= null){
                this.MajorVersion = obj.toString();
            }    
        }
        if (soapObject.hasProperty("MinorVersion"))
        {	
	        java.lang.Object obj = soapObject.getProperty("MinorVersion");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.MinorVersion = j.toString();
                }
	        }
	        else if (obj!= null){
                this.MinorVersion = obj.toString();
            }    
        }
        if (soapObject.hasProperty("RevisionVersion"))
        {	
	        java.lang.Object obj = soapObject.getProperty("RevisionVersion");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.RevisionVersion = j.toString();
                }
	        }
	        else if (obj!= null){
                this.RevisionVersion = obj.toString();
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using org.mbds.wolf.tsm.gp.systems.messaging2_1_0 version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return MajorVersion;
        }
        if(propertyIndex==1)
        {
            return MinorVersion;
        }
        if(propertyIndex==2)
        {
            return RevisionVersion!=null?RevisionVersion:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MajorVersion";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "MinorVersion";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "RevisionVersion";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
