package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------



import org.ksoap2.serialization.*;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;

public class SignatureValueType  
{
    
    public String value;
    
    public String Id;

    public SignatureValueType ()
    {
    }

    public SignatureValueType (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;


        if(inObj!=null)
        {
		    SoapPrimitive j =(SoapPrimitive)inObj;
            value = j.toString();
        }

        if (inObj.hasAttribute("Id"))
        {	
            java.lang.Object j = inObj.getAttribute("Id");
            if (j != null)
            {
	            Id = j.toString();
            }
        }

    }
    public Object getSimpleValue()
    {
        Object j=this.value;
        SoapPrimitive primitive = new SoapPrimitive("http://www.w3.org/2000/09/xmldsig#", "value",j!=null?j.toString():"");
        if (this.Id != null)
        {
            AttributeInfo attrInfo = new AttributeInfo();
            attrInfo.setName("Id");
            attrInfo.setValue(this.Id);
            attrInfo.setNamespace("");
            primitive.addAttribute(attrInfo);
        }
        return primitive;
    }}
