package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------



import java.io.IOException;
import java.io.StringReader;
import java.io.StringWriter;
import java.lang.reflect.Constructor;
import java.util.HashMap;
import java.util.Vector;

import org.ksoap2.SoapEnvelope;
import org.ksoap2.serialization.AttributeContainer;
import org.ksoap2.serialization.MarshalFloat;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;
import org.ksoap2.serialization.SoapSerializationEnvelope;
import org.kxml2.io.KXmlParser;
import org.kxml2.kdom.Element;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.AID;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.Address;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.ApplicationData;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.ApplicationLog;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.CRN;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.CardAuditTrail;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.CardConfiguration;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.CardConfigurationLog;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.CardCustomization;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.CollatorReturnCode;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.Data;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.DataSet;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.DeliveryModule;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.Entity;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.EntityID;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.Entity_Contact;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.Error;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.GenericModule;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.Information;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.LogIdentifierCode;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.MarshalDate;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.MarshalGuid;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.ModuleIdentifierCode;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.Person;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.PhysicalCardIdentifier;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.ProcessingStep;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.ProcessingStepResult;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.elements.RequestedDeliveryDate;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.*;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.ActivateServiceCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.ApplicationRegistryUpdateCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.BasicDiversified_CreateFirstSSDKeysetCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.BasicRandom_CreateFirstSSDKeysetCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.Basic_CreateFirstSSDKeysetCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.CCCMScenario1UsingPK_CreateFirstSSDKeysetCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.CCCMScenario2A_CreateFirstSSDKeysetCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.CCCMScenario2B_CreateFirstSSDKeysetCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.CCCMScenario3_CreateFirstSSDKeysetCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.CreateFirstSSDKeysetCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.DeleteCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.ExchangeServiceDataCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.ExtraditeCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.InstallServiceCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.InstantiateApplicationCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.LoadELFCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.MakeSelectableApplicationCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.PersonalizeServiceCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.SECommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.ServiceCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.SetStatusCommandType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.data.CCMCommandStatusType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.data.CommandStatusCodeDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.data.ServiceCommandStatusCodeDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.responses.ActivateServiceCommandResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.responses.BasicDiversified_CreateFirstSSDKeysetCommandResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.responses.BasicRandom_CreateFirstSSDKeysetCommandResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.responses.Basic_CreateFirstSSDKeysetCommandResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.responses.CCCMScenario2A_CreateFirstSSDKeysetCommandResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.responses.CCCMScenario2B_CreateFirstSSDKeysetCommandResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.responses.CCCMScenario3_CreateFirstSSDKeysetCommandResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.responses.CCMScenario1UsingPK_CreateFirstSSDKeysetCommandResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.responses.CreateFirstSSDKeysetCommandResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.responses.InstallServiceCommandResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.responses.InstantiateApplicationCommandResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.responses.PersonalizeServiceCommandResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.responses.SECommandResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.responses.ServiceCommandResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.results.ExchangeServiceDataCommandResultType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.results.SECommandResultType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.commands.results.ServiceCommandResultType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.BasicRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.BeginConversationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.BindDeviceApplicationToSEApplicationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.CheckGlobalEligibilityRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.CheckMobileSubscriptionEligibilityRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.DeclareServiceInstanceReferenceRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.DeleteDeviceApplicationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.DeleteSCWSServicePortalRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.DeployServiceRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.EndConversationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.EnrollSSDOwnerCertificateRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.ExchangeServiceDataRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.GenerateDMTokenRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.GetApplicationOrELFStatusRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.GetCAInformationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.GetDeviceCapabilityProfileIdRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.GetMobileSubscriptionAlternateIdentifierRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.GetMobileSubscriptionSEIdentifiersRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.GetSDFreeMemoryRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.GetSECapabilityProfileIdRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.GetSEMobileSubscriptionIdentifierRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.GetServiceInstanceReferenceDescriptorRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.GetServiceStateRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.HandleActionDoneOnDeviceApplicationNotificationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.HandleActionDoneOnServiceNotificationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.HandleEndServiceStateChangeNotificationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.HandleMobileSubscriptionIdentifierChangedNotificationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.HandleMobileSubscriptionStatusChangeNotificationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.HandleSEDeviceChangedNotificationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.HandleSEDeviceStatusChangeNotificationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.HandleSEMobileSubscriptionChangedNotificationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.HandleSERenewalNotificationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.HandleSEStatusChangeNotificationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.HandleServiceEnvironmentChangeNotificationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.HandleStartServiceStateChangeNotificationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.LoadDeviceApplicationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.LoadSCWSServicePortalRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.LookupServiceInstanceReferenceRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.SECommandsGenerationAndRemoteExecutionRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.SendScriptRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.SuspendOrResumeServiceRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.TerminateServiceRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.UnbindDeviceApplicationToSEApplicationRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.UpgradeServiceRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.VerifyDMReceiptRequestType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.BeginConversationResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.CheckGlobalEligibilityResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.CheckMobileSubscriptionEligibilityResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.DeclareServiceInstanceReferenceResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.DeleteDeviceApplicationResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.DeployServiceResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.EnrollSSDOwnerCertificateResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.ExchangeServiceDataStatusCodeDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.GetCAInformationResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.GetDeviceCapabilityProfileIdResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.GetMobileSubscriptionAlternateIdentifierResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.GetSDFreeMemoryResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.GetSECapabilityProfileIdResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.GetSEMobileSubscriptionIdentifierResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.GetServiceInstanceReferenceDescriptorResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.GetServiceStateResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.LoadDeviceApplicationResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.LookupServiceInstanceReferenceResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.SECommandsGenerationAndRemoteExecutionResponseResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.SendScriptResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.SuspendOrResumeServiceResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.TerminateServiceResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data.UpgradeServiceResponseDataType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.BasicResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.BeginConversationResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.BindDeviceApplicationToSEApplicationResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.CheckGlobalEligibilityResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.CheckMobileSubscriptionEligibilityResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.DeclareServiceInstanceReferenceResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.DeleteDeviceApplicationResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.DeleteSCWSServicePortalResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.DeployServiceResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.EndConversationResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.EnrollSSDOwnerCertificateResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.ExchangeServiceDataResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.GenerateDMTokenResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.GetApplicationOrELFStatusResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.GetCAInformationResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.GetDeviceCapabilityProfileIdResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.GetMobileSubscriptionAlternateIdentifierResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.GetMobileSubscriptionSEIdentifiersResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.GetSDFreeMemoryResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.GetSECapabilityProfileIdResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.GetSEMobileSubscriptionIdentifierResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.GetServiceInstanceReferenceDescriptorResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.GetServiceStateResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.LoadDeviceApplicationResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.LoadSCWSServicePortalResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.LookupServiceInstanceReferenceResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.SECommandsGenerationAndRemoteExecutionResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.SendScriptResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.SuspendOrResumeServiceResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.TerminateServiceResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.UnbindDeviceApplicationToSEApplicationResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.UpgradeServiceResponseType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.responses.VerifyDMReceiptResponseType;
import org.xmlpull.v1.XmlPullParser;
import org.xmlpull.v1.XmlPullParserFactory;
import org.xmlpull.v1.XmlSerializer;


public class ExtendedSoapSerializationEnvelope extends SoapSerializationEnvelope {
    static HashMap< java.lang.String,java.lang.Class> classNames = new HashMap< java.lang.String, java.lang.Class>();
    static {
        classNames.put("http://www.w3.org/2000/09/xmldsig#^^SignatureType",SignatureType.class);
        classNames.put("http://www.w3.org/2000/09/xmldsig#^^SignedInfoType",SignedInfoType.class);
        classNames.put("http://www.w3.org/2000/09/xmldsig#^^CanonicalizationMethodType",CanonicalizationMethodType.class);
        classNames.put("http://www.w3.org/2000/09/xmldsig#^^SignatureMethodType",SignatureMethodType.class);
        classNames.put("http://www.w3.org/2000/09/xmldsig#^^ReferenceType",ReferenceType.class);
        classNames.put("http://www.w3.org/2000/09/xmldsig#^^TransformType",TransformType.class);
        classNames.put("http://www.w3.org/2000/09/xmldsig#^^DigestMethodType",DigestMethodType.class);
        classNames.put("http://www.w3.org/2000/09/xmldsig#^^KeyInfoType",KeyInfoType.class);
        classNames.put("http://www.w3.org/2000/09/xmldsig#^^KeyValueType",KeyValueType.class);
        classNames.put("http://www.w3.org/2000/09/xmldsig#^^RetrievalMethodType",RetrievalMethodType.class);
        classNames.put("http://www.w3.org/2000/09/xmldsig#^^X509DataType",X509DataType.class);
        classNames.put("http://www.w3.org/2000/09/xmldsig#^^X509IssuerSerialType",X509IssuerSerialType.class);
        classNames.put("http://www.w3.org/2000/09/xmldsig#^^PGPDataType",PGPDataType.class);
        classNames.put("http://www.w3.org/2000/09/xmldsig#^^SPKIDataType",SPKIDataType.class);
        classNames.put("http://www.w3.org/2000/09/xmldsig#^^ObjectType",ObjectType.class);
        classNames.put("http://www.w3.org/2000/09/xmldsig#^^DSAKeyValueType",DSAKeyValueType.class);
        classNames.put("http://www.w3.org/2000/09/xmldsig#^^RSAKeyValueType",RSAKeyValueType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ExtensionsType",ExtensionsType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SEApplicationIdentifierType",SEApplicationIdentifierType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SEAppId_AIDType",SEAppId_AIDType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SEAppId_TARType",SEAppId_TARType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^MobileSubscriptionIdentifierType",MobileSubscriptionIdentifierType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^MSId_MSISDNType",MSId_MSISDNType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^MSId_AliasType",MSId_AliasType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^MSId_GenericType",MSId_GenericType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^MSId_ExtendableType",MSId_ExtendableType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SEIdentifierType",SEIdentifierType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SEId_CardUniqueDataType",SEId_CardUniqueDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SEId_ICCIDType",SEId_ICCIDType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SEId_GenericType",SEId_GenericType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SEId_ExtendableType",SEId_ExtendableType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ServiceVersionType",ServiceVersionType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ServiceIdentifierType",ServiceIdentifierType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ServiceQualifierType",ServiceQualifierType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ServiceInstanceReferenceType",ServiceInstanceReferenceType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^BasicRequestType",BasicRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^BasicResponseType",BasicResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ExecutionStatusType",ExecutionStatusType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^StatusCodeDataType",StatusCodeDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CheckGlobalEligibilityRequestType",CheckGlobalEligibilityRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CheckGlobalEligibilityResponseDataType",CheckGlobalEligibilityResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CheckGlobalEligibilityResponseType",CheckGlobalEligibilityResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetDeviceCapabilityProfileIdRequestType",GetDeviceCapabilityProfileIdRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetDeviceCapabilityProfileIdResponseDataType",GetDeviceCapabilityProfileIdResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetDeviceCapabilityProfileIdResponseType",GetDeviceCapabilityProfileIdResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetSECapabilityProfileIdRequestType",GetSECapabilityProfileIdRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetSECapabilityProfileIdResponseDataType",GetSECapabilityProfileIdResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetSECapabilityProfileIdResponseType",GetSECapabilityProfileIdResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CheckMobileSubscriptionEligibilityRequestType",CheckMobileSubscriptionEligibilityRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CheckMobileSubscriptionEligibilityResponseDataType",CheckMobileSubscriptionEligibilityResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CheckMobileSubscriptionEligibilityResponseType",CheckMobileSubscriptionEligibilityResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^HandleStartServiceStateChangeNotificationRequestType",HandleStartServiceStateChangeNotificationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^HandleEndServiceStateChangeNotificationRequestType",HandleEndServiceStateChangeNotificationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetMobileSubscriptionAlternateIdentifierRequestType",GetMobileSubscriptionAlternateIdentifierRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetMobileSubscriptionAlternateIdentifierResponseDataType",GetMobileSubscriptionAlternateIdentifierResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetMobileSubscriptionAlternateIdentifierResponseType",GetMobileSubscriptionAlternateIdentifierResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetSEMobileSubscriptionIdentifierRequestType",GetSEMobileSubscriptionIdentifierRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetSEMobileSubscriptionIdentifierResponseDataType",GetSEMobileSubscriptionIdentifierResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetSEMobileSubscriptionIdentifierResponseType",GetSEMobileSubscriptionIdentifierResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetMobileSubscriptionSEIdentifiersRequestType",GetMobileSubscriptionSEIdentifiersRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetMobileSubscriptionSEIdentifiersResponseType",GetMobileSubscriptionSEIdentifiersResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^HandleMobileSubscriptionIdentifierChangedNotificationRequestType",HandleMobileSubscriptionIdentifierChangedNotificationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^HandleMobileSubscriptionStatusChangeNotificationRequestType",HandleMobileSubscriptionStatusChangeNotificationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^HandleSERenewalNotificationRequestType",HandleSERenewalNotificationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^HandleSEDeviceChangedNotificationRequestType",HandleSEDeviceChangedNotificationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^HandleSEDeviceStatusChangeNotificationRequestType",HandleSEDeviceStatusChangeNotificationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^HandleSEMobileSubscriptionChangedNotificationRequestType",HandleSEMobileSubscriptionChangedNotificationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^HandleSEStatusChangeNotificationRequestType",HandleSEStatusChangeNotificationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^LookupServiceInstanceReferenceRequestType",LookupServiceInstanceReferenceRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^LookupServiceInstanceReferenceResponseDataType",LookupServiceInstanceReferenceResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^LookupServiceInstanceReferenceResponseType",LookupServiceInstanceReferenceResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^DeclareServiceInstanceReferenceRequestType",DeclareServiceInstanceReferenceRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^DeclareServiceInstanceReferenceResponseDataType",DeclareServiceInstanceReferenceResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^DeclareServiceInstanceReferenceResponseType",DeclareServiceInstanceReferenceResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetServiceInstanceReferenceDescriptorRequestType",GetServiceInstanceReferenceDescriptorRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetServiceInstanceReferenceDescriptorResponseDataType",GetServiceInstanceReferenceDescriptorResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetServiceInstanceReferenceDescriptorResponseType",GetServiceInstanceReferenceDescriptorResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetServiceStateRequestType",GetServiceStateRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetServiceStateResponseDataType",GetServiceStateResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetServiceStateResponseType",GetServiceStateResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ServiceCommandType",ServiceCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ServiceCommandResponseType",ServiceCommandResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^InstallServiceCommandType",InstallServiceCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^PersonalizeServiceCommandType",PersonalizeServiceCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ActivateServiceCommandType",ActivateServiceCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^InstallServiceCommandResponseType",InstallServiceCommandResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^PersonalizeServiceCommandResponseType",PersonalizeServiceCommandResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ActivateServiceCommandResponseType",ActivateServiceCommandResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^DeployServiceRequestType",DeployServiceRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ServiceCommandStatusCodeDataType",ServiceCommandStatusCodeDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ServiceCommandResultType",ServiceCommandResultType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^DeployServiceResponseDataType",DeployServiceResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^DeployServiceResponseType",DeployServiceResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^UpgradeServiceRequestType",UpgradeServiceRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^UpgradeServiceResponseDataType",UpgradeServiceResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^UpgradeServiceResponseType",UpgradeServiceResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ExchangeServiceDataCommandType",ExchangeServiceDataCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ExchangeServiceDataStatusCodeDataType",ExchangeServiceDataStatusCodeDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ExchangeServiceDataCommandResultType",ExchangeServiceDataCommandResultType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ExchangeServiceDataRequestType",ExchangeServiceDataRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ExchangeServiceDataResponseType",ExchangeServiceDataResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SuspendOrResumeServiceRequestType",SuspendOrResumeServiceRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SuspendOrResumeServiceResponseDataType",SuspendOrResumeServiceResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SuspendOrResumeServiceResponseType",SuspendOrResumeServiceResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^TerminateServiceRequestType",TerminateServiceRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^TerminateServiceResponseDataType",TerminateServiceResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^TerminateServiceResponseType",TerminateServiceResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^HandleServiceEnvironmentChangeNotificationRequestType",HandleServiceEnvironmentChangeNotificationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^HandleActionDoneOnServiceNotificationRequestType",HandleActionDoneOnServiceNotificationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^EnrollSSDOwnerCertificateRequestType",EnrollSSDOwnerCertificateRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^EnrollSSDOwnerCertificateResponseDataType",EnrollSSDOwnerCertificateResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^EnrollSSDOwnerCertificateResponseType",EnrollSSDOwnerCertificateResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetCAInformationRequestType",GetCAInformationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetCAInformationResponseDataType",GetCAInformationResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetCAInformationResponseType",GetCAInformationResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SECommandType",SECommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SECommandResponseType",SECommandResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^KeySetDescriptionType",KeySetDescriptionType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SimpleKeySetProfile_KeySetDescriptionType",SimpleKeySetProfile_KeySetDescriptionType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SCP81KeySetProfile_KeySetDescriptionType",SCP81KeySetProfile_KeySetDescriptionType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CreateFirstSSDKeysetCommandType",CreateFirstSSDKeysetCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SDKeyType",SDKeyType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^KeySetType",KeySetType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^Basic_CreateFirstSSDKeysetCommandType",Basic_CreateFirstSSDKeysetCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^BasicRandom_CreateFirstSSDKeysetCommandType",BasicRandom_CreateFirstSSDKeysetCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^BasicDiversified_CreateFirstSSDKeysetCommandType",BasicDiversified_CreateFirstSSDKeysetCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CCCMScenario1UsingPK_CreateFirstSSDKeysetCommandType",CCCMScenario1UsingPK_CreateFirstSSDKeysetCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CCCMScenario2A_CreateFirstSSDKeysetCommandType",CCCMScenario2A_CreateFirstSSDKeysetCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CCCMScenario2B_CreateFirstSSDKeysetCommandType",CCCMScenario2B_CreateFirstSSDKeysetCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CCCMScenario3_CreateFirstSSDKeysetCommandType",CCCMScenario3_CreateFirstSSDKeysetCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CreateFirstSSDKeysetCommandResponseType",CreateFirstSSDKeysetCommandResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^Basic_CreateFirstSSDKeysetCommandResponseType",Basic_CreateFirstSSDKeysetCommandResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^BasicRandom_CreateFirstSSDKeysetCommandResponseType",BasicRandom_CreateFirstSSDKeysetCommandResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^BasicDiversified_CreateFirstSSDKeysetCommandResponseType",BasicDiversified_CreateFirstSSDKeysetCommandResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CCMScenario1UsingPK_CreateFirstSSDKeysetCommandResponseType",CCMScenario1UsingPK_CreateFirstSSDKeysetCommandResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CCCMScenario2A_CreateFirstSSDKeysetCommandResponseType",CCCMScenario2A_CreateFirstSSDKeysetCommandResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CCCMScenario2B_CreateFirstSSDKeysetCommandResponseType",CCCMScenario2B_CreateFirstSSDKeysetCommandResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CCCMScenario3_CreateFirstSSDKeysetCommandResponseType",CCCMScenario3_CreateFirstSSDKeysetCommandResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^LoadELFCommandType",LoadELFCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^DAPBlockType",DAPBlockType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ExtraditeCommandType",ExtraditeCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^InstantiateApplicationCommandType",InstantiateApplicationCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^InstantiateApplicationCommandResponseType",InstantiateApplicationCommandResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^MakeSelectableApplicationCommandType",MakeSelectableApplicationCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ApplicationRegistryUpdateCommandType",ApplicationRegistryUpdateCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SetStatusCommandType",SetStatusCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^DeleteCommandType",DeleteCommandType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^MobileNFCServiceContextType",MobileNFCServiceContextType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SECommandsGenerationAndRemoteExecutionRequestType",SECommandsGenerationAndRemoteExecutionRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CommandStatusCodeDataType",CommandStatusCodeDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SECommandResultType",SECommandResultType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^MobileNFCServiceResultContextType",MobileNFCServiceResultContextType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SECommandsGenerationAndRemoteExecutionResponseResponseDataType",SECommandsGenerationAndRemoteExecutionResponseResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SECommandsGenerationAndRemoteExecutionResponseType",SECommandsGenerationAndRemoteExecutionResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GenerateDMTokenRequestType",GenerateDMTokenRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GenerateDMTokenResponseType",GenerateDMTokenResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CCMCommandStatusType",CCMCommandStatusType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^VerifyDMReceiptRequestType",VerifyDMReceiptRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^VerifyDMReceiptResponseType",VerifyDMReceiptResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^BeginConversationRequestType",BeginConversationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^BeginConversationResponseDataType",BeginConversationResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^BeginConversationResponseType",BeginConversationResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SendScriptRequestType",SendScriptRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SendScriptResponseDataType",SendScriptResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SendScriptResponseType",SendScriptResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^EndConversationRequestType",EndConversationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^EndConversationResponseType",EndConversationResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetApplicationOrELFStatusRequestType",GetApplicationOrELFStatusRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ComponentStatusType",ComponentStatusType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^Application_ComponentStatusType",Application_ComponentStatusType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^SD_ComponentStatusType",SD_ComponentStatusType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ELF_ComponentStatusType",ELF_ComponentStatusType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetApplicationOrELFStatusResponseType",GetApplicationOrELFStatusResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetSDFreeMemoryRequestType",GetSDFreeMemoryRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetSDFreeMemoryResponseDataType",GetSDFreeMemoryResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GetSDFreeMemoryResponseType",GetSDFreeMemoryResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^LoadSCWSServicePortalRequestType",LoadSCWSServicePortalRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^LoadSCWSServicePortalResponseType",LoadSCWSServicePortalResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^DeleteSCWSServicePortalRequestType",DeleteSCWSServicePortalRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^DeleteSCWSServicePortalResponseType",DeleteSCWSServicePortalResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^DeviceInstallationModeType",DeviceInstallationModeType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^LoadDeviceApplicationRequestType",LoadDeviceApplicationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^LoadDeviceApplicationResponseDataType",LoadDeviceApplicationResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^LoadDeviceApplicationResponseType",LoadDeviceApplicationResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^BindDeviceApplicationToSEApplicationRequestType",BindDeviceApplicationToSEApplicationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^BindDeviceApplicationToSEApplicationResponseType",BindDeviceApplicationToSEApplicationResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^DeviceDeletionModeType",DeviceDeletionModeType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^DeleteDeviceApplicationRequestType",DeleteDeviceApplicationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^DeleteDeviceApplicationResponseDataType",DeleteDeviceApplicationResponseDataType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^DeleteDeviceApplicationResponseType",DeleteDeviceApplicationResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^UnbindDeviceApplicationToSEApplicationRequestType",UnbindDeviceApplicationToSEApplicationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^UnbindDeviceApplicationToSEApplicationResponseType",UnbindDeviceApplicationToSEApplicationResponseType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^HandleActionDoneOnDeviceApplicationNotificationRequestType",HandleActionDoneOnDeviceApplicationNotificationRequestType.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ApplicationData",ApplicationData.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^AID",AID.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ProcessingStep",ProcessingStep.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^DataSet",DataSet.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^Data",Data.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ApplicationLog",ApplicationLog.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ProcessingStepResult",ProcessingStepResult.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^Error",Error.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^LogIdentifierCode",LogIdentifierCode.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CardConfigurationLog",CardConfigurationLog.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CollatorReturnCode",CollatorReturnCode.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CardCustomization",CardCustomization.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CardAuditTrail",CardAuditTrail.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^ModuleIdentifierCode",ModuleIdentifierCode.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CardConfiguration",CardConfiguration.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^CRN",CRN.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^PhysicalCardIdentifier",PhysicalCardIdentifier.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^Address",Address.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^Person",Person.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^Entity_Contact",Entity_Contact.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^Entity",Entity.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^EntityID",EntityID.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^Information",Information.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^GenericModule",GenericModule.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^DeliveryModule",DeliveryModule.class);
        classNames.put("http://namespaces.globalplatform.org/systems-messaging/2.1.0^^RequestedDeliveryDate",RequestedDeliveryDate.class);
    }   

    private final String MsNs="http://schemas.microsoft.com/2003/10/Serialization/";
    protected static final int QNAME_NAMESPACE = 0;
    private static final String TYPE_LABEL = "type";

    public ExtendedSoapSerializationEnvelope() {
        super(SoapEnvelope.VER11);
        implicitTypes = true;

        new MarshalGuid().register(this);
        new MarshalDate().register(this);
        new MarshalFloat().register(this);
    }

    

    @Override
    protected void writeProperty(XmlSerializer writer, java.lang.Object obj, PropertyInfo type) throws IOException {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if (obj == null || obj== SoapPrimitive.NullNilElement) {
            writer.attribute(xsi, version >= VER12 ? NIL_LABEL : NULL_LABEL, "true");
            return;
        }
            java.lang.Object[] qName = getInfo(null, obj);
            if (!type.multiRef && qName[2] == null)
            {
                if (!implicitTypes || (obj.getClass() != type.type && !(obj instanceof Vector ) && type.type!=String.class)) {
                    String xmlName=Helper.getKeyByValue(classNames,obj.getClass());
                    if(xmlName!=null)
                    {
                        java.lang.String[] parts=xmlName.split("\\^\\^");
                        java.lang.String prefix = writer.getPrefix(parts[0], true);
                        writer.attribute(xsi, TYPE_LABEL, prefix + ":" +parts[1]);
                    }
                    else
                    {
                        java.lang.String prefix = writer.getPrefix(type.namespace, true);
                        writer.attribute(xsi, TYPE_LABEL, prefix + ":" + obj.getClass().getSimpleName());
                    }
                }
                //super.writeProperty(writer,obj,type);

                //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
                //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
                writeElement(writer, obj, type, qName[QNAME_MARSHAL]);
            }
            else {
                super.writeProperty(writer, obj, type);
            }
    }

    public SoapObject GetExceptionDetail(Element detailElement) {
         Element errorElement=detailElement.getElement(0);
         return GetSoapObject(errorElement);
    }

    public SoapObject GetSoapObject(Element detailElement) {
        try{
            XmlSerializer xmlSerializer = XmlPullParserFactory.newInstance().newSerializer();
            StringWriter writer = new StringWriter();
            xmlSerializer.setOutput(writer);
            detailElement.write(xmlSerializer);
            xmlSerializer.flush();

            XmlPullParser xpp = new KXmlParser();
            xpp.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, true);

            xpp.setInput(new StringReader(writer.toString()));
            xpp.nextTag();
            SoapObject soapObj = new SoapObject(detailElement.getNamespace(),detailElement.getName());
            readSerializable(xpp,soapObj);
            return soapObj;
        }
        catch (java.lang.Exception ex)
        {
            ex.printStackTrace();
        }
        return null;
    }

    public java.lang.Object GetHeader(Element detailElement) {
        if(detailElement.getText(0)!=null)
        {
            SoapPrimitive primitive = new SoapPrimitive(detailElement.getNamespace(),detailElement.getName(),detailElement.getText(0));
            return  primitive;
        }
    
        return GetSoapObject(detailElement);
    }
    

    public java.lang.Object get(java.lang.Object soap,java.lang.Class cl)
    {
        if(soap==null)
        {
            return null;
        }
        try
        {
            if(soap instanceof  Vector)
            {
                Constructor ctor = cl.getConstructor(Vector.class,ExtendedSoapSerializationEnvelope.class);
                return ctor.newInstance(soap,this);
            }
            {
                if(soap instanceof SoapObject)
                {
                    java.lang.String key=String.format("%s^^%s",((SoapObject)soap).getNamespace(),((SoapObject)soap).getName());
                    if(classNames.containsKey(key))
                    {
                        cl=classNames.get(key);
                    }
                }
                Constructor ctor = cl.getConstructor(AttributeContainer.class,ExtendedSoapSerializationEnvelope.class);
                return ctor.newInstance(soap,this);
            }
        }
        catch (java.lang.Exception ex)
        {
            ex.printStackTrace();
            return null;
        }
    }
} 

