package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.requests.data;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;


import org.ksoap2.serialization.*;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.MobileSubscriptionIdentifierType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.SEIdentifierType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.ServiceIdentifierType;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.ServiceQualifierType;

public class GetServiceInstanceReferenceDescriptorResponseDataType extends AttributeContainer implements KvmSerializable
{
    
    public ServiceIdentifierType Service;
    
    public ServiceQualifierType ServiceQualifier;
    
    public SEIdentifierType SecureElement;
    
    public MobileSubscriptionIdentifierType MobileSubscription;

    public GetServiceInstanceReferenceDescriptorResponseDataType ()
    {
    }

    public GetServiceInstanceReferenceDescriptorResponseDataType (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("Service"))
        {	
	        java.lang.Object j = soapObject.getProperty("Service");
	        this.Service = (ServiceIdentifierType)envelope.get(j,ServiceIdentifierType.class);
        }
        if (soapObject.hasProperty("ServiceQualifier"))
        {	
	        java.lang.Object j = soapObject.getProperty("ServiceQualifier");
	        this.ServiceQualifier = (ServiceQualifierType)envelope.get(j,ServiceQualifierType.class);
        }
        if (soapObject.hasProperty("SecureElement"))
        {	
	        java.lang.Object j = soapObject.getProperty("SecureElement");
	        this.SecureElement = (SEIdentifierType)envelope.get(j,SEIdentifierType.class);
        }
        if (soapObject.hasProperty("MobileSubscription"))
        {	
	        java.lang.Object j = soapObject.getProperty("MobileSubscription");
	        this.MobileSubscription = (MobileSubscriptionIdentifierType)envelope.get(j,MobileSubscriptionIdentifierType.class);
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using org.mbds.wolf.tsm.gp.systems.messaging2_1_0 version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return Service;
        }
        if(propertyIndex==1)
        {
            return ServiceQualifier!=null?ServiceQualifier:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return SecureElement;
        }
        if(propertyIndex==3)
        {
            return MobileSubscription!=null?MobileSubscription:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = ServiceIdentifierType.class;
            info.name = "Service";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==1)
        {
            info.type = ServiceQualifierType.class;
            info.name = "ServiceQualifier";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==2)
        {
            info.type = SEIdentifierType.class;
            info.name = "SecureElement";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==3)
        {
            info.type = MobileSubscriptionIdentifierType.class;
            info.name = "MobileSubscription";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
