package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.elements;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;


import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;

public class Address extends AttributeContainer implements KvmSerializable
{
    
    public ArrayList< String>StreetAddress =new ArrayList<String>();
    
    public String City;
    
    public String State;
    
    public String Zip;
    
    public String Country;

    public Address ()
    {
    }

    public Address (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("StreetAddress"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.StreetAddress = new ArrayList<String>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("StreetAddress"))
	            {
                    java.lang.Object j =info.getValue();
	                String j1= j.toString();
	                this.StreetAddress.add(j1);
	            }
	        }
        }
        if (soapObject.hasProperty("City"))
        {	
	        java.lang.Object obj = soapObject.getProperty("City");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.City = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.City = (String)obj;
            }    
        }
        if (soapObject.hasProperty("State"))
        {	
	        java.lang.Object obj = soapObject.getProperty("State");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.State = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.State = (String)obj;
            }    
        }
        if (soapObject.hasProperty("Zip"))
        {	
	        java.lang.Object obj = soapObject.getProperty("Zip");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Zip = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.Zip = (String)obj;
            }    
        }
        if (soapObject.hasProperty("Country"))
        {	
	        java.lang.Object obj = soapObject.getProperty("Country");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.Country = j.toString();
                }
	        }
	        else if (obj!= null && obj instanceof String){
                this.Country = (String)obj;
            }    
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using org.mbds.wolf.tsm.gp.systems.messaging2_1_0 version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return City!=null?City:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return State!=null?State:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==2)
        {
            return Zip!=null?Zip:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==3)
        {
            return Country!=null?Country:SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=+4 && propertyIndex< + 4+this.StreetAddress.size())
        {
            return StreetAddress.get(propertyIndex-(+4));
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4+StreetAddress.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "City";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "State";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Zip";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "Country";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex>=+4 && propertyIndex <= +4+this.StreetAddress.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "StreetAddress";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
