package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.elements;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;


import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.SEIdentifierType;

public class CardConfiguration extends AttributeContainer implements KvmSerializable
{
    
    public CRN CRN;
    
    public SEIdentifierType SecureElementId;
    
    public ArrayList< String>ValidCardProfileID =new ArrayList<String>();
    
    public ArrayList< AID>AID =new ArrayList<AID>();
    
    public String CollatorStatus;

    public CardConfiguration ()
    {
    }

    public CardConfiguration (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("CRN"))
        {	
	        java.lang.Object j = soapObject.getProperty("CRN");
	        this.CRN = (CRN)envelope.get(j,CRN.class);
        }
        if (soapObject.hasProperty("SecureElementId"))
        {	
	        java.lang.Object j = soapObject.getProperty("SecureElementId");
	        this.SecureElementId = (SEIdentifierType)envelope.get(j,SEIdentifierType.class);
        }
        if (soapObject.hasProperty("ValidCardProfileID"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.ValidCardProfileID = new ArrayList<String>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("ValidCardProfileID"))
	            {
                    java.lang.Object j =info.getValue();
	                String j1= j.toString();
	                this.ValidCardProfileID.add(j1);
	            }
	        }
        }
        if (soapObject.hasProperty("AID"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.AID = new ArrayList<AID>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("AID"))
	            {
                    java.lang.Object j =info.getValue();
	                AID j1= (AID)envelope.get(j,AID.class);
	                this.AID.add(j1);
	            }
	        }
        }


        if (inObj.hasAttribute("CollatorStatus"))
        {	
            java.lang.Object j = inObj.getAttribute("CollatorStatus");
            if (j != null)
            {
	            CollatorStatus = j.toString();
            }
        }

    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using org.mbds.wolf.tsm.gp.systems.messaging2_1_0 version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return CRN;
        }
        if(propertyIndex==1)
        {
            return SecureElementId!=null?SecureElementId:SoapPrimitive.NullSkip;
        }
        if(propertyIndex>=+2 && propertyIndex< + 2+this.ValidCardProfileID.size())
        {
            return ValidCardProfileID.get(propertyIndex-(+2));
        }
        if(propertyIndex>=+2+this.ValidCardProfileID.size() && propertyIndex< + 2+this.ValidCardProfileID.size()+this.AID.size())
        {
            return AID.get(propertyIndex-(+2+this.ValidCardProfileID.size()));
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 2+ValidCardProfileID.size()+AID.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = CRN.class;
            info.name = "CRN";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==1)
        {
            info.type = SEIdentifierType.class;
            info.name = "SecureElementId";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex>=+2 && propertyIndex <= +2+this.ValidCardProfileID.size())
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ValidCardProfileID";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex>=+2+this.ValidCardProfileID.size() && propertyIndex <= +2+this.ValidCardProfileID.size()+this.AID.size())
        {
            info.type = AID.class;
            info.name = "AID";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }


    @Override
    public int getAttributeCount() {
        return 1;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "CollatorStatus";
            info.namespace= "";
            info.setValue(CollatorStatus);
        }
    }}
