package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.elements;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;


import org.ksoap2.serialization.*;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;

public class DeliveryModule extends AttributeContainer implements KvmSerializable
{
    
    public EntityID EntityID;
    
    public Entity Entity;
    
    public RequestedDeliveryDate RequestedDeliveryDate;
    
    public ShippingInformation ShippingInformation=new ShippingInformation();
    
    public PackagingInformation PackagingInformation=new PackagingInformation();

    public DeliveryModule ()
    {
    }

    public DeliveryModule (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("EntityID"))
        {	
	        java.lang.Object j = soapObject.getProperty("EntityID");
	        this.EntityID = (EntityID)envelope.get(j,EntityID.class);
        }
        if (soapObject.hasProperty("Entity"))
        {	
	        java.lang.Object j = soapObject.getProperty("Entity");
	        this.Entity = (Entity)envelope.get(j,Entity.class);
        }
        if (soapObject.hasProperty("RequestedDeliveryDate"))
        {	
	        java.lang.Object j = soapObject.getProperty("RequestedDeliveryDate");
	        this.RequestedDeliveryDate = (RequestedDeliveryDate)envelope.get(j,RequestedDeliveryDate.class);
        }
        if (soapObject.hasProperty("ShippingInformation"))
        {	
	        java.lang.Object j = soapObject.getProperty("ShippingInformation");
	        this.ShippingInformation = new ShippingInformation((AttributeContainer)j,envelope);
        }
        if (soapObject.hasProperty("PackagingInformation"))
        {	
	        java.lang.Object j = soapObject.getProperty("PackagingInformation");
	        this.PackagingInformation = new PackagingInformation((AttributeContainer)j,envelope);
        }


    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using org.mbds.wolf.tsm.gp.systems.messaging2_1_0 version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return EntityID;
        }
        if(propertyIndex==1)
        {
            return Entity;
        }
        if(propertyIndex==2)
        {
            return RequestedDeliveryDate;
        }
        if(propertyIndex==3)
        {
            return ShippingInformation;
        }
        if(propertyIndex==4)
        {
            return PackagingInformation;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 5;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = EntityID.class;
            info.name = "EntityID";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==1)
        {
            info.type = Entity.class;
            info.name = "Entity";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==2)
        {
            info.type = RequestedDeliveryDate.class;
            info.name = "RequestedDeliveryDate";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==3)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "ShippingInformation";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==4)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "PackagingInformation";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }

}
