package org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.elements;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.5
//
// Created by amlesas Development at 08-07-2014
//
//---------------------------------------------------


import java.util.Hashtable;


import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.ExtendedSoapSerializationEnvelope;
import org.mbds.wolf.tsm.gp.systems.messaging2_1_0.ksoap2.services.types.SignatureType;

public class GenericModule extends AttributeContainer implements KvmSerializable
{
    
    public String ProfileUniqueID;
    
    public ArrayList< ProcessingStep>ProcessingStep =new ArrayList<ProcessingStep>();
    
    public LogData LogData=new LogData();
    
    public ModuleData ModuleData=new ModuleData();
    
    public SignatureType Signature;
    
    public String ModuleName;
    
    public String Identifier;

    public GenericModule ()
    {
    }

    public GenericModule (AttributeContainer inObj,ExtendedSoapSerializationEnvelope envelope)
    {
	    
	    if (inObj == null)
            return;



        SoapObject soapObject=(SoapObject)inObj;  
        if (soapObject.hasProperty("ProfileUniqueID"))
        {	
	        java.lang.Object obj = soapObject.getProperty("ProfileUniqueID");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class))
            {
                SoapPrimitive j =(SoapPrimitive) obj;
                if(j.toString()!=null)
                {
                    this.ProfileUniqueID = j.toString();
                }
	        }
	        else if (obj!= null){
                this.ProfileUniqueID = obj.toString();
            }    
        }
        if (soapObject.hasProperty("ProcessingStep"))
        {	
	        int size = soapObject.getPropertyCount();
	        this.ProcessingStep = new ArrayList<ProcessingStep>();
	        for (int i0=0;i0< size;i0++)
	        {
	            PropertyInfo info=new PropertyInfo();
	            soapObject.getPropertyInfo(i0, info);
                java.lang.Object obj = info.getValue();
	            if (obj!=null && info.name.equals("ProcessingStep"))
	            {
                    java.lang.Object j =info.getValue();
	                ProcessingStep j1= (ProcessingStep)envelope.get(j,ProcessingStep.class);
	                this.ProcessingStep.add(j1);
	            }
	        }
        }
        if (soapObject.hasProperty("LogData"))
        {	
	        java.lang.Object j = soapObject.getProperty("LogData");
	        this.LogData = new LogData((AttributeContainer)j,envelope);
        }
        if (soapObject.hasProperty("ModuleData"))
        {	
	        java.lang.Object j = soapObject.getProperty("ModuleData");
	        this.ModuleData = new ModuleData((AttributeContainer)j,envelope);
        }
        if (soapObject.hasProperty("Signature"))
        {	
	        java.lang.Object j = soapObject.getProperty("Signature");
	        this.Signature = (SignatureType)envelope.get(j,SignatureType.class);
        }


        if (inObj.hasAttribute("ModuleName"))
        {	
            java.lang.Object j = inObj.getAttribute("ModuleName");
            if (j != null)
            {
	            ModuleName = j.toString();
            }
        }

        if (inObj.hasAttribute("Identifier"))
        {	
            java.lang.Object j = inObj.getAttribute("Identifier");
            if (j != null)
            {
	            Identifier = j.toString();
            }
        }

    }

    @Override
    public java.lang.Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using org.mbds.wolf.tsm.gp.systems.messaging2_1_0 version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return ProfileUniqueID;
        }
        if(propertyIndex==1)
        {
            return LogData;
        }
        if(propertyIndex==2)
        {
            return ModuleData;
        }
        if(propertyIndex==3)
        {
            return Signature;
        }
        if(propertyIndex>=+4 && propertyIndex< + 4+this.ProcessingStep.size())
        {
            return ProcessingStep.get(propertyIndex-(+4));
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 4+ProcessingStep.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "ProfileUniqueID";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==1)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "LogData";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.VECTOR_CLASS;
            info.name = "ModuleData";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
        if(propertyIndex==3)
        {
            info.type = SignatureType.class;
            info.name = "Signature";
            info.namespace= "http://www.w3.org/2000/09/xmldsig#";
        }
        if(propertyIndex>=+4 && propertyIndex <= +4+this.ProcessingStep.size())
        {
            info.type = ProcessingStep.class;
            info.name = "ProcessingStep";
            info.namespace= "http://namespaces.globalplatform.org/systems-messaging/2.1.0";
        }
    }
    
    @Override
    public void setProperty(int arg0, java.lang.Object arg1)
    {
    }


    @Override
    public int getAttributeCount() {
        return 2;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "ModuleName";
            info.namespace= "";
            info.setValue(ModuleName);
        }
        if(index==1)
        {
            info.name = "Identifier";
            info.namespace= "";
            info.setValue(Identifier);
        }
    }}
